
GET http://localhost:3000/api/profile

####
POST http://localhost:3000/api/profile
Content-Type: application/json

{
    "name": "Hung Do"
}

####
PATCH http://localhost:3000/api/profile/7
Content-Type: application/json

{
    "name": "Hung Do"
}